### ISSUE TITLE
Agents using SM

### ISSUE THREAD

**Issue by ArseniyNikonov** [tobiasvanderwerff/C20-Civil-Violence#10]
Right now it is implemented in a way that every tick roughly a certain number of agents use SM. Is it better to implement it in a way where it is defined during agent generation? If we do it like that we will have a subset of agents that never uses social media and just mind their own business. It feels more plausible to me. Also, that should slightly change overall behaviour when protest exist since right now some agents won't go to protest at a particular tick but overall they are still moving towards the protest.

**Comment by tobiasvanderwerff** [comment]
I actually already implemented this, at spawn time agents are given a boolean property 'sm-user' that indicates whether they are a social media user or not.
