### ISSUE TITLE
Why does a high social media response rate cause fewer civil unrest?

### ISSUE THREAD

**Issue by tobiasvanderwerff** [tobiasvanderwerff/C20-Civil-Violence#21]
In section 3.1.1 of the report, it says: 

"Another interesting observation was that whenever the agent social media response rate was high, overall unrest seemed to be lower. This is shown in Fig. \ref{fig:quiet-jailed-active-exp1-2}. A possible explanation for this is that \dots".

Come up with an explanation for why this happens.

**Comment by Wehzie** [comment]
We are waiting for the feedback to see if what Panas wrote on the report regarding your question does make sense.

**Comment by Wehzie** [comment]
Got feedback. Wasn't criticized specifically. Tobias will read over report again.
