### ISSUE TITLE
Resolving agents blocking each other

### ISSUE THREAD

**Issue by Wehzie** [tobiasvanderwerff/C20-Civil-Violence#5]
With many agents and cops in the simulation the probability of them blocking each other is high when movement is limited to be from one directly connected patch to another.
A solution could be that movement need have variable range in essence jumping over multiple patches in one tick.
Another solution could be allowing multiple agents on one patch. It has to checked whether this is possible in Netlogo.

**Comment by ArseniyNikonov** [comment]
I'll work on it in the weekend

**Comment by ArseniyNikonov** [comment]
If i understand it correctly fd function implemented using jumps so i think if we have a slightly higher value of fd (i've tried 3) it seems to solve the problem at least partially.
I also added some random movement using fd 3 and it seems to work quite well. If agents go to the protest and protest stops they spread away nicely from the center.
