### ISSUE TITLE
Should all cops go to the centroid? 

### ISSUE THREAD

**Issue by tobiasvanderwerff** [tobiasvanderwerff/C20-Civil-Violence#9]
Something to consider: do we want all cops to go to the centroid? Would it make more sense if some percentage of cops went there? You can imagine that in a real-life scenario, even though cops monitor social media, not all cops are sent to a social media protest, due to possible underpopultation in other areas.

**Comment by Wehzie** [comment]
It makes sense if only a percentage of cops go to the centroid. The percentage should be set by a slider.

**Comment by Wehzie** [comment]
On discussion we agreed to implement a slider to indicate that there is a parameter at play. However we agree that it is unlikely the parameter will be modified during experimentation. We think a value of 50% cop response to social media is plausible as initial value, further experimentation may result in deciding on another value.

**Comment by Wehzie** [comment]
We implemented this.
